from app.db import Base, SessionLocal, engine


def test_database_foundation_uses_psycopg_with_mvp_tables() -> None:
    assert engine.url.drivername == "postgresql+psycopg"
    assert SessionLocal.kw["bind"] is engine
    assert set(Base.metadata.tables) == {
        "action_generation_executions",
        "action_groups",
        "action_items",
        "action_status_history",
        "agent_artifacts",
        "agent_checkpoints",
        "agent_events",
        "agent_executions",
        "agent_runs",
        "agent_steps",
        "action_matching_executions",
        "action_repository_matches",
        "analysis_findings",
        "analysis_diagnostics",
        "analysis_interpretations",
        "analysis_results",
        "analysis_runs",
        "analysis_scores",
        "detected_technologies",
        "discovery_runs",
        "page_analysis_runs",
        "performance_snapshots",
        "accessibility_audits",
        "accessibility_findings",
        "accessibility_nodes",
        "manual_review_checklists",
        "projects",
        "repository_connections",
        "repository_file_index",
        "repository_scan_executions",
        "report_artifacts",
        "report_executions",
        "report_sections",
        "report_snapshots",
        "site_diagnostic_executions",
        "site_diagnostic_findings",
        "site_diagnostic_occurrences",
        "score_executions",
        "score_snapshots",
        "category_scores",
        "metric_contributions",
        "score_explanations",
        "website_pages",
        "websites",
    }
