from app.schemas.metadata import MetricCategoryEnum, MetricDefinition, MetricValueTypeEnum

_METRICS = [
    MetricDefinition(
        metric_id="overall_score",
        label="Overall Score",
        category=MetricCategoryEnum.SITE_SCORE,
        description="overall score of the site",
        explanation=("overall site score calculated across all categories"),
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="performance_score",
        label="Performance Score",
        category=MetricCategoryEnum.CATEGORY_SCORE,
        description="performance score",
        explanation="performance category score",
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="accessibility_score",
        label="Accessibility Score",
        category=MetricCategoryEnum.CATEGORY_SCORE,
        description="accessibility score",
        explanation="accessibility category score",
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="seo_score",
        label="SEO Score",
        category=MetricCategoryEnum.CATEGORY_SCORE,
        description="SEO score",
        explanation="SEO category score",
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="best_practices_score",
        label="Best Practices Score",
        category=MetricCategoryEnum.CATEGORY_SCORE,
        description="best practices score",
        explanation="best practices category score",
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="technical_quality_score",
        label="Technical Quality Score",
        category=MetricCategoryEnum.CATEGORY_SCORE,
        description="technical quality score",
        explanation="technical quality category score",
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="security_score",
        label="Security Score",
        category=MetricCategoryEnum.CATEGORY_SCORE,
        description="security score",
        explanation="security category score",
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="page_score",
        label="Page Score",
        category=MetricCategoryEnum.PAGE_SCORE,
        description="individual page score",
        explanation="overall score for a single page",
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="category_score",
        label="Category Score",
        category=MetricCategoryEnum.CATEGORY_SCORE,
        description="category score",
        explanation="generic category score",
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="priority_score",
        label="Priority Score",
        category=MetricCategoryEnum.ACTION_PLAN,
        description="issue priority score",
        explanation="priority score for an action item",
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="discovered_pages",
        label="Discovered Pages",
        category=MetricCategoryEnum.COVERAGE,
        description="discovered pages",
        explanation="total number of discovered URLs",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="eligible_pages",
        label="Eligible Pages",
        category=MetricCategoryEnum.COVERAGE,
        description="eligible pages",
        explanation="pages eligible for analysis",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="selected_pages",
        label="Selected Pages",
        category=MetricCategoryEnum.COVERAGE,
        description="selected pages",
        explanation="pages selected for level 2",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="analyzed_pages",
        label="Analyzed Pages",
        category=MetricCategoryEnum.COVERAGE,
        description="analyzed pages",
        explanation="pages that received some analysis",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="successful_pages",
        label="Successful Pages",
        category=MetricCategoryEnum.COVERAGE,
        description="successful pages",
        explanation="pages analyzed successfully",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="partial_pages",
        label="Partial Pages",
        category=MetricCategoryEnum.COVERAGE,
        description="partial pages",
        explanation="pages with partial analysis",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="failed_pages",
        label="Failed Pages",
        category=MetricCategoryEnum.COVERAGE,
        description="failed pages",
        explanation="pages that failed analysis completely",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="skipped_pages",
        label="Skipped Pages",
        category=MetricCategoryEnum.COVERAGE,
        description="skipped pages",
        explanation="pages skipped during analysis",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="unanalyzed_eligible_pages",
        label="Unanalyzed Eligible",
        category=MetricCategoryEnum.COVERAGE,
        description="unanalyzed eligible pages",
        explanation="eligible pages that were not analyzed",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="level_1_attempted",
        label="Level 1 Attempted",
        category=MetricCategoryEnum.COVERAGE,
        description="L1 attempted",
        explanation="pages where level 1 was attempted",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="level_1_successful",
        label="Level 1 Successful",
        category=MetricCategoryEnum.COVERAGE,
        description="L1 successful",
        explanation="pages where level 1 was successful",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="level_1_failed",
        label="Level 1 Failed",
        category=MetricCategoryEnum.COVERAGE,
        description="L1 failed",
        explanation="pages where level 1 failed",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="level_1_partial",
        label="Level 1 Partial",
        category=MetricCategoryEnum.COVERAGE,
        description="L1 partial",
        explanation="pages where level 1 was partial",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="level_2_attempted",
        label="Level 2 Attempted",
        category=MetricCategoryEnum.COVERAGE,
        description="L2 attempted",
        explanation="pages where level 2 was attempted",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="level_2_successful",
        label="Level 2 Successful",
        category=MetricCategoryEnum.COVERAGE,
        description="L2 successful",
        explanation="pages where level 2 was successful",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="level_2_failed",
        label="Level 2 Failed",
        category=MetricCategoryEnum.COVERAGE,
        description="L2 failed",
        explanation="pages where level 2 failed",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="level_2_partial",
        label="Level 2 Partial",
        category=MetricCategoryEnum.COVERAGE,
        description="L2 partial",
        explanation="pages where level 2 was partial",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="analysis_coverage_percent",
        label="Analysis Coverage",
        category=MetricCategoryEnum.COVERAGE,
        description="analysis coverage",
        explanation="percentage of eligible pages analyzed",
        value_type=MetricValueTypeEnum.PERCENTAGE,
        unit="%",
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="clean_pass_percent",
        label="Clean Pass Percentage",
        category=MetricCategoryEnum.COVERAGE,
        description="clean pass percentage",
        explanation="percentage of pages with no issues",
        value_type=MetricValueTypeEnum.PERCENTAGE,
        unit="%",
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="severity",
        label="Severity",
        category=MetricCategoryEnum.ACTION_PLAN,
        description="severity level",
        explanation="severity level of the issue",
        value_type=MetricValueTypeEnum.TEXT,
        unit=None,
        display_scale=None,
        min_value=None,
        max_value=None,
        higher_is_better=None,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="confidence",
        label="Confidence",
        category=MetricCategoryEnum.ACTION_PLAN,
        description="confidence level",
        explanation="confidence in the finding",
        value_type=MetricValueTypeEnum.PERCENTAGE,
        unit="%",
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="estimated_effort",
        label="Estimated Effort",
        category=MetricCategoryEnum.ACTION_PLAN,
        description="estimated effort",
        explanation="estimated effort to resolve",
        value_type=MetricValueTypeEnum.TEXT,
        unit=None,
        display_scale=None,
        min_value=None,
        max_value=None,
        higher_is_better=None,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="affected_page_count",
        label="Affected Page Count",
        category=MetricCategoryEnum.ACTION_PLAN,
        description="affected pages",
        explanation="number of pages affected by the issue",
        value_type=MetricValueTypeEnum.COUNT,
        unit="pages",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="average_priority",
        label="Average Priority",
        category=MetricCategoryEnum.ACTION_PLAN,
        description="average priority",
        explanation="average priority of issues",
        value_type=MetricValueTypeEnum.SCORE,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="generation_coverage",
        label="Generation Coverage",
        category=MetricCategoryEnum.ACTION_PLAN,
        description="generation coverage",
        explanation="coverage of action generation",
        value_type=MetricValueTypeEnum.PERCENTAGE,
        unit="%",
        display_scale=None,
        min_value=0.0,
        max_value=100.0,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="files_discovered",
        label="Files Discovered",
        category=MetricCategoryEnum.REPOSITORY,
        description="discovered files",
        explanation="number of files discovered",
        value_type=MetricValueTypeEnum.COUNT,
        unit="files",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="eligible_files",
        label="Eligible Files",
        category=MetricCategoryEnum.REPOSITORY,
        description="eligible files",
        explanation="number of files eligible for scanning",
        value_type=MetricValueTypeEnum.COUNT,
        unit="files",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="scanned_files",
        label="Scanned Files",
        category=MetricCategoryEnum.REPOSITORY,
        description="scanned files",
        explanation="number of files scanned",
        value_type=MetricValueTypeEnum.COUNT,
        unit="files",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="skipped_files",
        label="Skipped Files",
        category=MetricCategoryEnum.REPOSITORY,
        description="skipped files",
        explanation="number of files skipped",
        value_type=MetricValueTypeEnum.COUNT,
        unit="files",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="failed_files",
        label="Failed Files",
        category=MetricCategoryEnum.REPOSITORY,
        description="failed files",
        explanation="number of files that failed scanning",
        value_type=MetricValueTypeEnum.COUNT,
        unit="files",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="framework_confidence",
        label="Framework Confidence",
        category=MetricCategoryEnum.REPOSITORY,
        description="framework confidence",
        explanation="confidence in the detected framework",
        value_type=MetricValueTypeEnum.TEXT,
        unit=None,
        display_scale=None,
        min_value=None,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="repository_match_confidence",
        label="Repository Match Confidence",
        category=MetricCategoryEnum.REPOSITORY,
        description="repo match confidence",
        explanation="confidence in repository issue matching",
        value_type=MetricValueTypeEnum.TEXT,
        unit=None,
        display_scale=None,
        min_value=None,
        max_value=None,
        higher_is_better=True,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="repository_location_status",
        label="Repository Location Status",
        category=MetricCategoryEnum.REPOSITORY,
        description="repo location status",
        explanation=("status of the repository location mapping"),
        value_type=MetricValueTypeEnum.STATUS,
        unit=None,
        display_scale=None,
        min_value=None,
        max_value=None,
        higher_is_better=None,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="lcp",
        label="LCP",
        category=MetricCategoryEnum.PERFORMANCE,
        description="largest contentful paint",
        explanation="largest contentful paint duration",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="inp",
        label="INP",
        category=MetricCategoryEnum.PERFORMANCE,
        description="interaction to next paint",
        explanation="interaction to next paint duration",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="cls",
        label="CLS",
        category=MetricCategoryEnum.PERFORMANCE,
        description="cumulative layout shift",
        explanation="cumulative layout shift ratio",
        value_type=MetricValueTypeEnum.RATIO,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="fcp",
        label="FCP",
        category=MetricCategoryEnum.PERFORMANCE,
        description="first contentful paint",
        explanation="first contentful paint duration",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="speed_index",
        label="Speed Index",
        category=MetricCategoryEnum.PERFORMANCE,
        description="speed index",
        explanation="speed index duration",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="total_blocking_time",
        label="Total Blocking Time",
        category=MetricCategoryEnum.PERFORMANCE,
        description="total blocking time",
        explanation="total blocking time duration",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="tti",
        label="TTI",
        category=MetricCategoryEnum.PERFORMANCE,
        description="time to interactive",
        explanation="time to interactive duration",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="server_response_timing",
        label="Server Response Time",
        category=MetricCategoryEnum.PERFORMANCE,
        description="server response time",
        explanation="server response duration",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="resource_count",
        label="Resource Count",
        category=MetricCategoryEnum.PERFORMANCE,
        description="resource count",
        explanation="total number of loaded resources",
        value_type=MetricValueTypeEnum.COUNT,
        unit="resources",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="transferred_resource_size",
        label="Transferred Size",
        category=MetricCategoryEnum.PERFORMANCE,
        description="transferred size",
        explanation="total bytes transferred",
        value_type=MetricValueTypeEnum.BYTES,
        unit="bytes",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="System",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="No specific limitations noted.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="lighthouse_lcp",
        label="Lighthouse LCP",
        category=MetricCategoryEnum.PERFORMANCE,
        description="lighthouse largest contentful paint",
        explanation="simulated largest contentful paint duration in lab",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="Lighthouse",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="Lab metric only.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="lighthouse_cls",
        label="Lighthouse CLS",
        category=MetricCategoryEnum.PERFORMANCE,
        description="lighthouse cumulative layout shift",
        explanation="simulated cumulative layout shift ratio in lab",
        value_type=MetricValueTypeEnum.RATIO,
        unit=None,
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="Lighthouse",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="Lab metric only.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="lighthouse_tbt",
        label="Lighthouse TBT",
        category=MetricCategoryEnum.PERFORMANCE,
        description="lighthouse total blocking time",
        explanation="simulated total blocking time in lab",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="Lighthouse",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="Lab metric only.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="lighthouse_fcp",
        label="Lighthouse FCP",
        category=MetricCategoryEnum.PERFORMANCE,
        description="lighthouse first contentful paint",
        explanation="simulated first contentful paint in lab",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="Lighthouse",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="Lab metric only.",
        confidence_applicability="Not applicable.",
    ),
    MetricDefinition(
        metric_id="lighthouse_speed_index",
        label="Lighthouse Speed Index",
        category=MetricCategoryEnum.PERFORMANCE,
        description="lighthouse speed index",
        explanation="simulated speed index in lab",
        value_type=MetricValueTypeEnum.DURATION,
        unit="ms",
        display_scale=None,
        min_value=0.0,
        max_value=None,
        higher_is_better=False,
        evidence_source="Lighthouse",
        calculation_summary=("See methodology documentation for exact formula details."),
        interpretation_guidance=("Refer to the applicable profile for thresholds."),
        known_limitations="Lab metric only.",
        confidence_applicability="Not applicable.",
    ),
]

METRICS_REGISTRY = {m.metric_id: m for m in _METRICS}


def get_all_metrics(
    category: MetricCategoryEnum | None = None,
    value_type: MetricValueTypeEnum | None = None,
) -> list[MetricDefinition]:
    filtered = list(METRICS_REGISTRY.values())
    if category:
        filtered = [m for m in filtered if m.category == category]
    if value_type:
        filtered = [m for m in filtered if m.value_type == value_type]
    return sorted(filtered, key=lambda m: m.metric_id)


def get_metric(metric_id: str) -> MetricDefinition | None:
    return METRICS_REGISTRY.get(metric_id)


def register_metric(metric: MetricDefinition) -> None:
    if metric.metric_id in METRICS_REGISTRY:
        raise ValueError(f"Metric {metric.metric_id} already registered.")
    METRICS_REGISTRY[metric.metric_id] = metric


METRICS_REGISTRY.update(
    {
        "field_lcp": MetricDefinition(
            metric_id="field_lcp",
            label="Field LCP",
            category=MetricCategoryEnum.PERFORMANCE,
            description="Largest Contentful Paint measured in the field",
            explanation=(
                "Represents real-user experience at the 75th percentile, collected by the "
                "Chrome User Experience Report (CrUX)."
            ),
            value_type=MetricValueTypeEnum.DURATION,
            unit="ms",
            display_scale=None,
            min_value=0,
            max_value=None,
            higher_is_better=False,
            evidence_source="CrUX real-user p75 evidence",
            calculation_summary="CrUX p75 over the last 28 days.",
            interpretation_guidance="Values under 2500ms are good. Evaluate alongside Lab LCP.",
            known_limitations="Only available for public URLs with sufficient Chrome traffic.",
            confidence_applicability="High confidence for real-world representation.",
        ),
        "field_inp": MetricDefinition(
            metric_id="field_inp",
            label="Field INP",
            category=MetricCategoryEnum.PERFORMANCE,
            description="Interaction to Next Paint measured in the field",
            explanation=(
                "Represents real-user interactivity responsiveness at the 75th percentile, "
                "collected by CrUX."
            ),
            value_type=MetricValueTypeEnum.DURATION,
            unit="ms",
            display_scale=None,
            min_value=0,
            max_value=None,
            higher_is_better=False,
            evidence_source="CrUX real-user p75 evidence",
            calculation_summary="CrUX p75 over the last 28 days.",
            interpretation_guidance="Values under 200ms are good.",
            known_limitations="Only available for public URLs with sufficient Chrome traffic.",
            confidence_applicability="High confidence for real-world representation.",
        ),
        "field_cls": MetricDefinition(
            metric_id="field_cls",
            label="Field CLS",
            category=MetricCategoryEnum.PERFORMANCE,
            description="Cumulative Layout Shift measured in the field",
            explanation=(
                "Represents real-user visual stability at the 75th percentile, collected by CrUX."
            ),
            value_type=MetricValueTypeEnum.RATIO,
            unit=None,
            display_scale=None,
            min_value=0,
            max_value=None,
            higher_is_better=False,
            evidence_source="CrUX real-user p75 evidence",
            calculation_summary="CrUX p75 over the last 28 days.",
            interpretation_guidance="Values under 0.1 are good.",
            known_limitations="Only available for public URLs with sufficient Chrome traffic.",
            confidence_applicability="High confidence for real-world representation.",
        ),
        "lab_fcp": MetricDefinition(
            metric_id="lab_fcp",
            label="Lab FCP",
            category=MetricCategoryEnum.PERFORMANCE,
            description="First Contentful Paint measured in a controlled lab environment",
            explanation=(
                "Simulated load time collected via Lighthouse, representing a single specific "
                "test condition."
            ),
            value_type=MetricValueTypeEnum.DURATION,
            unit="ms",
            display_scale=None,
            min_value=0,
            max_value=None,
            higher_is_better=False,
            evidence_source="Lighthouse controlled test evidence",
            calculation_summary="Lighthouse simulated measurement.",
            interpretation_guidance="Use to debug issues detected in Field data.",
            known_limitations="Does not capture real-world network variability.",
            confidence_applicability="Highly reproducible for diagnostic purposes.",
        ),
        "lab_lcp": MetricDefinition(
            metric_id="lab_lcp",
            label="Lab LCP",
            category=MetricCategoryEnum.PERFORMANCE,
            description="Largest Contentful Paint measured in a controlled lab environment",
            explanation=(
                "Simulated load time collected via Lighthouse, representing a single specific "
                "test condition."
            ),
            value_type=MetricValueTypeEnum.DURATION,
            unit="ms",
            display_scale=None,
            min_value=0,
            max_value=None,
            higher_is_better=False,
            evidence_source="Lighthouse controlled test evidence",
            calculation_summary="Lighthouse simulated measurement.",
            interpretation_guidance="Use to debug issues detected in Field data.",
            known_limitations="Does not capture real-world network variability.",
            confidence_applicability="Highly reproducible for diagnostic purposes.",
        ),
        "lab_cls": MetricDefinition(
            metric_id="lab_cls",
            label="Lab CLS",
            category=MetricCategoryEnum.PERFORMANCE,
            description="Cumulative Layout Shift measured in a controlled lab environment",
            explanation=(
                "Simulated visual stability collected via Lighthouse, representing a single "
                "specific test condition."
            ),
            value_type=MetricValueTypeEnum.RATIO,
            unit=None,
            display_scale=None,
            min_value=0,
            max_value=None,
            higher_is_better=False,
            evidence_source="Lighthouse controlled test evidence",
            calculation_summary="Lighthouse simulated measurement.",
            interpretation_guidance="Use to debug issues detected in Field data.",
            known_limitations="Does not capture real-world network variability.",
            confidence_applicability="Highly reproducible for diagnostic purposes.",
        ),
        "lab_tbt": MetricDefinition(
            metric_id="lab_tbt",
            label="Lab TBT",
            category=MetricCategoryEnum.PERFORMANCE,
            description="Total Blocking Time measured in a controlled lab environment",
            explanation=(
                "Lighthouse Total Blocking Time. Note: TBT is a lab diagnostic metric and is "
                "NOT equivalent to Field INP, though they correlate."
            ),
            value_type=MetricValueTypeEnum.DURATION,
            unit="ms",
            display_scale=None,
            min_value=0,
            max_value=None,
            higher_is_better=False,
            evidence_source="Lighthouse controlled test evidence",
            calculation_summary="Lighthouse simulated measurement.",
            interpretation_guidance="Use to debug main-thread blocking detected in Field data.",
            known_limitations="Does not capture real-world network variability.",
            confidence_applicability="Highly reproducible for diagnostic purposes.",
        ),
        "lab_speed_index": MetricDefinition(
            metric_id="lab_speed_index",
            label="Lab Speed Index",
            category=MetricCategoryEnum.PERFORMANCE,
            description="Speed Index measured in a controlled lab environment",
            explanation=(
                "Simulated visual progression collected via Lighthouse, representing a single "
                "specific test condition."
            ),
            value_type=MetricValueTypeEnum.DURATION,
            unit="ms",
            display_scale=None,
            min_value=0,
            max_value=None,
            higher_is_better=False,
            evidence_source="Lighthouse controlled test evidence",
            calculation_summary="Lighthouse simulated measurement.",
            interpretation_guidance="Use to debug issues detected in Field data.",
            known_limitations="Does not capture real-world network variability.",
            confidence_applicability="Highly reproducible for diagnostic purposes.",
        ),
        "accessibility_violation_count": MetricDefinition(
            metric_id="accessibility_violation_count",
            label="Accessibility Violations",
            category=MetricCategoryEnum.ACCESSIBILITY,
            description="Number of automated accessibility violations.",
            explanation="The total number of accessibility failures detected by automated engines.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="issues",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="axe-core, Lighthouse",
            calculation_summary="Sum of all findings marked as violations.",
            interpretation_guidance=(
                "Any violations indicate a definitive failure of WCAG criteria."
            ),
            known_limitations="Automated tools cannot catch all accessibility issues.",
            confidence_applicability="High confidence for identified violations.",
        ),
        "accessibility_critical_count": MetricDefinition(
            metric_id="accessibility_critical_count",
            label="Critical Accessibility Issues",
            category=MetricCategoryEnum.ACCESSIBILITY,
            description="Number of critical accessibility issues.",
            explanation="Accessibility failures classified as critical impact.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="issues",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="axe-core",
            calculation_summary="Count of findings with critical impact.",
            interpretation_guidance="Must be fixed immediately.",
            known_limitations="Automated tools cannot catch all accessibility issues.",
            confidence_applicability="High confidence for identified violations.",
        ),
        "accessibility_serious_count": MetricDefinition(
            metric_id="accessibility_serious_count",
            label="Serious Accessibility Issues",
            category=MetricCategoryEnum.ACCESSIBILITY,
            description="Number of serious accessibility issues.",
            explanation="Accessibility failures classified as serious impact.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="issues",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="axe-core",
            calculation_summary="Count of findings with serious impact.",
            interpretation_guidance="Should be fixed soon.",
            known_limitations="Automated tools cannot catch all accessibility issues.",
            confidence_applicability="High confidence for identified violations.",
        ),
        "accessibility_moderate_count": MetricDefinition(
            metric_id="accessibility_moderate_count",
            label="Moderate Accessibility Issues",
            category=MetricCategoryEnum.ACCESSIBILITY,
            description="Number of moderate accessibility issues.",
            explanation="Accessibility failures classified as moderate impact.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="issues",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="axe-core",
            calculation_summary="Count of findings with moderate impact.",
            interpretation_guidance="Should be fixed.",
            known_limitations="Automated tools cannot catch all accessibility issues.",
            confidence_applicability="High confidence for identified violations.",
        ),
        "accessibility_minor_count": MetricDefinition(
            metric_id="accessibility_minor_count",
            label="Minor Accessibility Issues",
            category=MetricCategoryEnum.ACCESSIBILITY,
            description="Number of minor accessibility issues.",
            explanation="Accessibility failures classified as minor impact.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="issues",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="axe-core",
            calculation_summary="Count of findings with minor impact.",
            interpretation_guidance="Should be fixed when possible.",
            known_limitations="Automated tools cannot catch all accessibility issues.",
            confidence_applicability="High confidence for identified violations.",
        ),
        "accessibility_incomplete_count": MetricDefinition(
            metric_id="accessibility_incomplete_count",
            label="Incomplete Accessibility Reviews",
            category=MetricCategoryEnum.ACCESSIBILITY,
            description="Number of incomplete accessibility tests.",
            explanation=(
                "Tests that could not be fully evaluated automatically and require manual review."
            ),
            value_type=MetricValueTypeEnum.COUNT,
            unit="items",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="axe-core, Lighthouse",
            calculation_summary="Count of findings marked as incomplete.",
            interpretation_guidance="Must be manually verified.",
            known_limitations="Automated tools cannot fully evaluate these.",
            confidence_applicability="Requires human judgement.",
        ),
        "accessibility_manual_review_count": MetricDefinition(
            metric_id="accessibility_manual_review_count",
            label="Manual Review Required",
            category=MetricCategoryEnum.ACCESSIBILITY,
            description="Number of items requiring manual accessibility review.",
            explanation="Accessibility criteria that require human verification.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="items",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of manual review checklist items.",
            interpretation_guidance="Complete the manual review to verify compliance.",
            known_limitations="Depends on human expertise.",
            confidence_applicability="Dependent on human reviewer.",
        ),
        "accessibility_affected_page_count": MetricDefinition(
            metric_id="accessibility_affected_page_count",
            label="Accessibility Affected Pages",
            category=MetricCategoryEnum.ACCESSIBILITY,
            description="Number of pages with accessibility issues.",
            explanation="The total number of pages where accessibility violations were found.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="pages",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of unique pages with accessibility violations.",
            interpretation_guidance="Indicates the spread of accessibility issues.",
            known_limitations="Only covers analyzed pages.",
            confidence_applicability="High confidence for analyzed pages.",
        ),
        "site_diagnostic_finding_count": MetricDefinition(
            metric_id="site_diagnostic_finding_count",
            label="Total Diagnostic Findings",
            category=MetricCategoryEnum.TECHNICAL_QUALITY,
            description="Total number of site diagnostic findings.",
            explanation="Sum of all findings generated by the site diagnostics engine.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="findings",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of all findings.",
            interpretation_guidance="Lower is better.",
            known_limitations="Requires complete site analysis.",
            confidence_applicability="Depends on evidence coverage.",
        ),
        "sitewide_finding_count": MetricDefinition(
            metric_id="sitewide_finding_count",
            label="Site-Wide Findings",
            category=MetricCategoryEnum.TECHNICAL_QUALITY,
            description="Number of findings affecting the entire site.",
            explanation="Findings that have a site-wide scope.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="findings",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of findings with scope=site.",
            interpretation_guidance="Lower is better.",
            known_limitations="Requires complete site analysis.",
            confidence_applicability="Depends on evidence coverage.",
        ),
        "template_finding_count": MetricDefinition(
            metric_id="template_finding_count",
            label="Template Findings",
            category=MetricCategoryEnum.TECHNICAL_QUALITY,
            description="Number of findings affecting templates.",
            explanation="Findings that are clustered into repeated templates.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="findings",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of findings with scope=template.",
            interpretation_guidance="Lower is better.",
            known_limitations="Clustering relies on DOM and metadata heuristics.",
            confidence_applicability="Depends on evidence coverage.",
        ),
        "isolated_page_finding_count": MetricDefinition(
            metric_id="isolated_page_finding_count",
            label="Isolated Page Findings",
            category=MetricCategoryEnum.TECHNICAL_QUALITY,
            description="Number of findings affecting isolated pages.",
            explanation="Findings that have a page scope.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="findings",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of findings with scope=page.",
            interpretation_guidance="Lower is better.",
            known_limitations="Requires complete site analysis.",
            confidence_applicability="Depends on evidence coverage.",
        ),
        "internal_broken_link_count": MetricDefinition(
            metric_id="internal_broken_link_count",
            label="Internal Broken Links",
            category=MetricCategoryEnum.TECHNICAL_QUALITY,
            description="Number of broken internal links.",
            explanation="Internal links that point to a non-existent or error page.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="links",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of unique broken internal link targets.",
            interpretation_guidance="Lower is better. Fix broken links to improve user experience.",
            known_limitations="Depends on crawl depth.",
            confidence_applicability="High confidence for crawled pages.",
        ),
        "orphan_page_count": MetricDefinition(
            metric_id="orphan_page_count",
            label="Orphan Pages",
            category=MetricCategoryEnum.SEO,
            description="Number of pages with no inbound internal links.",
            explanation="Pages that cannot be reached by clicking links from other pages on the site.",  # noqa: E501
            value_type=MetricValueTypeEnum.COUNT,
            unit="pages",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of discovered pages with 0 internal inbound links.",
            interpretation_guidance="Lower is better.",
            known_limitations="Depends on complete site crawl.",
            confidence_applicability="High confidence for crawled pages.",
        ),
        "dead_end_page_count": MetricDefinition(
            metric_id="dead_end_page_count",
            label="Dead-End Pages",
            category=MetricCategoryEnum.SEO,
            description="Number of pages with no outbound links.",
            explanation="Pages that do not link to any other page on the site.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="pages",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of analyzed pages with 0 outbound links.",
            interpretation_guidance="Lower is better.",
            known_limitations="Depends on complete site analysis.",
            confidence_applicability="High confidence for analyzed pages.",
        ),
        "canonical_conflict_count": MetricDefinition(
            metric_id="canonical_conflict_count",
            label="Canonical Conflicts",
            category=MetricCategoryEnum.SEO,
            description="Number of canonical tag conflicts.",
            explanation="Pages with conflicting, missing, or malformed canonical tags.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="conflicts",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of canonical-related findings.",
            interpretation_guidance="Lower is better.",
            known_limitations="Technical indexability only, not actual search engine indexing.",
            confidence_applicability="High confidence for analyzed pages.",
        ),
        "duplicate_title_group_count": MetricDefinition(
            metric_id="duplicate_title_group_count",
            label="Duplicate Title Groups",
            category=MetricCategoryEnum.SEO,
            description="Number of groups of pages with duplicate titles.",
            explanation="Groups of pages that share the exact same title tag.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="groups",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of unique title strings shared by multiple pages.",
            interpretation_guidance="Lower is better.",
            known_limitations="Depends on complete site analysis.",
            confidence_applicability="High confidence for analyzed pages.",
        ),
        "duplicate_description_group_count": MetricDefinition(
            metric_id="duplicate_description_group_count",
            label="Duplicate Description Groups",
            category=MetricCategoryEnum.SEO,
            description="Number of groups of pages with duplicate descriptions.",
            explanation="Groups of pages that share the exact same meta description.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="groups",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of unique description strings shared by multiple pages.",
            interpretation_guidance="Lower is better.",
            known_limitations="Depends on complete site analysis.",
            confidence_applicability="High confidence for analyzed pages.",
        ),
        "near_duplicate_page_group_count": MetricDefinition(
            metric_id="near_duplicate_page_group_count",
            label="Near-Duplicate Page Groups",
            category=MetricCategoryEnum.SEO,
            description="Number of groups of near-duplicate pages.",
            explanation="Groups of pages with very similar content signatures.",
            value_type=MetricValueTypeEnum.COUNT,
            unit="groups",
            display_scale=None,
            min_value=0.0,
            max_value=None,
            higher_is_better=False,
            evidence_source="System",
            calculation_summary="Count of near-duplicate page clusters.",
            interpretation_guidance="Lower is better.",
            known_limitations="Relies on deterministic signatures; may have false positives.",
            confidence_applicability="Depends on signature threshold.",
        ),
        "site_diagnostic_coverage_percentage": MetricDefinition(
            metric_id="site_diagnostic_coverage_percentage",
            label="Site Diagnostic Coverage",
            category=MetricCategoryEnum.TECHNICAL_QUALITY,
            description="Percentage of site covered by diagnostics.",
            explanation="Ratio of analyzed pages to discovered pages.",
            value_type=MetricValueTypeEnum.PERCENTAGE,
            unit="%",
            display_scale=None,
            min_value=0.0,
            max_value=100.0,
            higher_is_better=True,
            evidence_source="System",
            calculation_summary="Analyzed pages / Discovered pages * 100",
            interpretation_guidance="Higher is better.",
            known_limitations="Coverage percentage is not a compliance score.",
            confidence_applicability="High confidence.",
        ),
    }
)
