"""accessibility intelligence

Revision ID: 20260725_0014
Revises: 20260725_0013
Create Date: 2026-07-25 14:00:00.000000

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20260725_0014"
down_revision = "20260725_0013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accessibility_audits",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("execution_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("website_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("analysis_run_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("page_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("normalized_url", sa.String(length=2048), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("provider_version", sa.String(length=50), nullable=True),
        sa.Column("ruleset_version", sa.String(length=50), nullable=True),
        sa.Column("profile_id", sa.String(length=100), nullable=True),
        sa.Column("profile_version", sa.String(length=50), nullable=True),
        sa.Column("requested_wcag_level", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("violation_count", sa.Integer(), nullable=True),
        sa.Column("incomplete_count", sa.Integer(), nullable=True),
        sa.Column("pass_count", sa.Integer(), nullable=True),
        sa.Column("inapplicable_count", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "execution_id",
            "website_id",
            "normalized_url",
            "provider",
            name="uq_accessibility_audits_execution_provider",
        ),
    )
    op.create_index(
        op.f("ix_accessibility_audits_analysis_run_id"),
        "accessibility_audits",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_audits_normalized_url"),
        "accessibility_audits",
        ["normalized_url"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_audits_page_id"),
        "accessibility_audits",
        ["page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_audits_website_id"),
        "accessibility_audits",
        ["website_id"],
        unique=False,
    )

    op.create_table(
        "accessibility_findings",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("audit_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("provider_rule_id", sa.String(length=255), nullable=False),
        sa.Column("act_rule_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("help_text", sa.Text(), nullable=True),
        sa.Column("help_url", sa.String(length=2048), nullable=True),
        sa.Column("impact", sa.String(length=50), nullable=False),
        sa.Column("result_type", sa.String(length=50), nullable=False),
        sa.Column("wcag_version", sa.String(length=50), nullable=True),
        sa.Column("wcag_criteria", sa.JSON(), nullable=True),
        sa.Column("conformance_level", sa.String(length=50), nullable=True),
        sa.Column("affected_element_count", sa.Integer(), nullable=False),
        sa.Column("remediation_summary", sa.Text(), nullable=True),
        sa.Column("manual_verification_required", sa.Boolean(), nullable=False),
        sa.Column("source_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["accessibility_audits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_accessibility_findings_audit_id"),
        "accessibility_findings",
        ["audit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_findings_provider_rule_id"),
        "accessibility_findings",
        ["provider_rule_id"],
        unique=False,
    )

    op.create_table(
        "manual_review_checklists",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("audit_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("checklist_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("applicable_wcag_criterion", sa.String(length=255), nullable=True),
        sa.Column("required_evidence", sa.Text(), nullable=True),
        sa.Column("suggested_test_procedure", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("automated_evidence_references", sa.JSON(), nullable=True),
        sa.Column("limitation_statement", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["accessibility_audits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manual_review_checklists_audit_id"),
        "manual_review_checklists",
        ["audit_id"],
        unique=False,
    )

    op.create_table(
        "accessibility_nodes",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("finding_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("normalized_selector", sa.Text(), nullable=False),
        sa.Column("html_excerpt", sa.Text(), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column("related_nodes", sa.JSON(), nullable=True),
        sa.Column("frame_context", sa.Text(), nullable=True),
        sa.Column("shadow_dom_context", sa.Text(), nullable=True),
        sa.Column("occurrence_fingerprint", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["accessibility_findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_accessibility_nodes_finding_id"),
        "accessibility_nodes",
        ["finding_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_nodes_occurrence_fingerprint"),
        "accessibility_nodes",
        ["occurrence_fingerprint"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_accessibility_nodes_occurrence_fingerprint"),
        table_name="accessibility_nodes",
    )
    op.drop_index(op.f("ix_accessibility_nodes_finding_id"), table_name="accessibility_nodes")
    op.drop_table("accessibility_nodes")
    op.drop_index(
        op.f("ix_manual_review_checklists_audit_id"),
        table_name="manual_review_checklists",
    )
    op.drop_table("manual_review_checklists")
    op.drop_index(
        op.f("ix_accessibility_findings_provider_rule_id"),
        table_name="accessibility_findings",
    )
    op.drop_index(op.f("ix_accessibility_findings_audit_id"), table_name="accessibility_findings")
    op.drop_table("accessibility_findings")
    op.drop_index(op.f("ix_accessibility_audits_website_id"), table_name="accessibility_audits")
    op.drop_index(op.f("ix_accessibility_audits_page_id"), table_name="accessibility_audits")
    op.drop_index(
        op.f("ix_accessibility_audits_normalized_url"),
        table_name="accessibility_audits",
    )
    op.drop_index(
        op.f("ix_accessibility_audits_analysis_run_id"),
        table_name="accessibility_audits",
    )
    op.drop_table("accessibility_audits")
    # ### end Alembic commands ###
